=== MarcMeketonVillanova/2024_RAS_PSC/JSON_schemas/input_problem_schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "file:///c:",
    "title": "RAS 2024 Problem Solving Competition - problem schema",
    "type": "object",
    "properties": {
      "problem_name": {
        "type": "string"
      },
      "yard_type": {"enum": ["through", "stub"]},
      "parameters": {
        "type": "object",
        "properties": {
          "alpha_a": {
            "type": "number"
          },
          "alpha_d": {
            "type": "number"
          },
          "beta_a": {
            "type": "number"
          },
          "beta_d": {
            "type": "number"
          },
          "track_speed_kph": {
            "type": "number"
          },
          "ladder_speed_kph": {
            "type": "number"
          },
          "wagon_length_m": {
              "type": "number"
          }
        },
        "required": [
          "alpha_a",
          "alpha_d",
          "beta_a",
          "beta_d",
          "track_speed_kph",
          "ladder_speed_kph",
          "wagon_length_m"
        ]
      },
      "track_lengths_m": {
        "type": "array",
        "items": {
          "type": "number"
        }
      },
      "left_lead_m": {"type": "number"},
      "right_lead_m": {"type": "number", "default": 0},
      "track_occupancies": {
        "type": "object",
        "additionalProperties": {
          "type": "array",
          "items": {
            "type": "integer"
          }
        },
        "propertyNames": {
          "type": "string"
        }
      },    
      "desired_block_order": {
        "type": "array",
        "items": {
          "type": "integer"
        }
      },
      "other_blocks_to_form": {
        "type": "array",
        "items": {
          "type": "integer"
        }
      }
    },
    "required": [
      "problem_name",
      "yard_type",
      "parameters",
      "track_lengths_m",
      "left_lead_m",
      "right_lead_m",
      "track_occupancies",
      "desired_block_order",
      "other_blocks_to_form"
    ]
  }

=== MarcMeketonVillanova/2024_RAS_PSC/input_problem_data/example_100_wagons_13_tracks.json
{
    "problem_name": "Big_Example",
    "yard_type": "stub",
    "parameters": {
        "alpha_a": 6750,
        "alpha_d": 6750,
        "beta_a": 292.5,
        "beta_d": 225,
        "track_speed_kph": 16,
        "ladder_speed_kph": 10,
        "wagon_length_m": 15
        },
    "track_lengths_m": [2000, 1800, 1700, 800, 700, 600, 500, 400, 300, 200, 200, 100],
    "left_lead_m": 2000,
    "right_lead_m":   0,
    "track_occupancies": {
        "1": [6, 12, 13, 9, 10, 12, 6, 1, 1, 2, 13, 8, 13, 7, 10, 3, 5, 6, 3, 5, 12, 13, 11, 13, 3, 5, 8, 8, 10, 2],
        "2": [8, 1, 7, 10, 10, 8, 7, 10, 2, 1, 13, 2, 9, 9, 4, 11, 10, 9, 8, 4, 7, 6, 2],
        "3": [10, 4, 5, 9, 2, 12, 13, 11, 5, 1, 4, 10, 3, 1, 5, 10, 3, 8, 8, 11, 10, 9, 7, 10],
        "4": [4, 8, 8, 5, 12, 6, 10, 4, 7, 9, 1, 3, 11, 8, 8, 10, 8, 4, 13, 11, 1, 9, 8]
        },
    "desired_block_order": [1, 2, 3, 4, 13, 8, 7, 9, 5, 6, 12],
    "other_blocks_to_form": [10, 11]
  }
